---
- name: test set facts
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: get reachable hosts
    wait_for:
     host: "{{ item }}"
     port: 22
     state: started
     delay: 0
     timeout: 1
    loop: "{{ groups['all'] }}"

  - name: set fact
    set_fact:
     host_number: 1
     test_var: "ok"
    loop: "{{ groups['all'] }}"

  - name: display facts
    shell: echo "{{ test_var }}"
    when: hostvars['localhost'].host_number == 1
